# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Proposed_UIVsamui.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCalendarWidget, QComboBox, QFrame,
    QGraphicsView, QHeaderView, QLabel, QMainWindow,
    QPlainTextEdit, QProgressBar, QPushButton, QScrollBar,
    QSizePolicy, QTabWidget, QTableWidget, QTableWidgetItem,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(826, 587)
        MainWindow.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(6, 39, 821, 551))
        font = QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.tabWidget.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.tabWidget.setStyleSheet(u"QTabBar::tab:selected {\n"
"    font: bold;\n"
"}\n"
"")
        self.Tab5 = QWidget()
        self.Tab5.setObjectName(u"Tab5")
        self.pushButton_14 = QPushButton(self.Tab5)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(330, 470, 181, 31))
        self.pushButton_14.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        icon = QIcon()
        icon.addFile(u"Images/icons8-download-48.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_14.setIcon(icon)
        self.graphicsView_6 = QGraphicsView(self.Tab5)
        self.graphicsView_6.setObjectName(u"graphicsView_6")
        self.graphicsView_6.setGeometry(QRect(30, 50, 751, 271))
        self.label_36 = QLabel(self.Tab5)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 10, 641, 30))
        self.label_36.setMinimumSize(QSize(641, 21))
        self.label_36.setMaximumSize(QSize(641, 30))
        font1 = QFont()
        font1.setPointSize(16)
        font1.setBold(True)
        self.label_36.setFont(font1)
        self.label_36.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.label_37 = QLabel(self.Tab5)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(330, 140, 171, 81))
        self.label_38 = QLabel(self.Tab5)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(30, 320, 141, 31))
        self.textEdit_3 = QTextEdit(self.Tab5)
        self.textEdit_3.setObjectName(u"textEdit_3")
        self.textEdit_3.setGeometry(QRect(30, 350, 751, 111))
        icon1 = QIcon()
        icon1.addFile(u"Images/icons8-reports-48.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tabWidget.addTab(self.Tab5, icon1, "")
        self.Tab4 = QWidget()
        self.Tab4.setObjectName(u"Tab4")
        self.frame = QFrame(self.Tab4)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(30, 50, 751, 291))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.graphicsView_5 = QGraphicsView(self.frame)
        self.graphicsView_5.setObjectName(u"graphicsView_5")
        self.graphicsView_5.setGeometry(QRect(15, 11, 471, 271))
        self.label_35 = QLabel(self.frame)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(190, 110, 121, 61))
        self.label_28 = QLabel(self.frame)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(630, 50, 81, 20))
        self.label_30 = QLabel(self.frame)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(630, 110, 91, 20))
        self.label_33 = QLabel(self.frame)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(520, 70, 101, 16))
        self.label_26 = QLabel(self.frame)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(510, 10, 111, 31))
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(True)
        self.label_26.setFont(font2)
        self.label_31 = QLabel(self.frame)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(520, 90, 101, 16))
        self.label_27 = QLabel(self.frame)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(520, 50, 101, 16))
        self.label_34 = QLabel(self.frame)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(630, 70, 81, 20))
        self.label_32 = QLabel(self.frame)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(630, 90, 81, 20))
        self.label_29 = QLabel(self.frame)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(520, 110, 101, 16))
        self.pushButton_12 = QPushButton(self.frame)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(520, 160, 91, 31))
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet(u"background-color: rgb(0, 170, 0);")
        self.pushButton_13 = QPushButton(self.frame)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(620, 160, 91, 31))
        self.pushButton_13.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.label_25 = QLabel(self.Tab4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 10, 641, 30))
        self.label_25.setMinimumSize(QSize(641, 21))
        self.label_25.setMaximumSize(QSize(641, 30))
        self.label_25.setFont(font1)
        self.label_25.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.tableWidget = QTableWidget(self.Tab4)
        if (self.tableWidget.columnCount() < 5):
            self.tableWidget.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        if (self.tableWidget.rowCount() < 1):
            self.tableWidget.setRowCount(1)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget.setItem(0, 0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget.setItem(0, 1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget.setItem(0, 2, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget.setItem(0, 3, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget.setItem(0, 4, __qtablewidgetitem9)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(30, 350, 751, 121))
        self.tableWidget.setContextMenuPolicy(Qt.ContextMenuPolicy.PreventContextMenu)
        self.tableWidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.verticalScrollBar = QScrollBar(self.Tab4)
        self.verticalScrollBar.setObjectName(u"verticalScrollBar")
        self.verticalScrollBar.setGeometry(QRect(795, 0, 21, 521))
        self.verticalScrollBar.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.verticalScrollBar.setOrientation(Qt.Orientation.Vertical)
        self.pushButton_17 = QPushButton(self.Tab4)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(30, 480, 101, 31))
        self.pushButton_17.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        icon2 = QIcon()
        icon2.addFile(u"Images/icons8-previous-48.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_17.setIcon(icon2)
        self.pushButton_16 = QPushButton(self.Tab4)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(680, 480, 101, 31))
        self.pushButton_16.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        icon3 = QIcon()
        icon3.addFile(u"Images/icons8-submit-document-48.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_16.setIcon(icon3)
        icon4 = QIcon()
        icon4.addFile(u"Images/icons8-result-48.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tabWidget.addTab(self.Tab4, icon4, "")
        self.Tab3 = QWidget()
        self.Tab3.setObjectName(u"Tab3")
        self.graphicsView_3 = QGraphicsView(self.Tab3)
        self.graphicsView_3.setObjectName(u"graphicsView_3")
        self.graphicsView_3.setGeometry(QRect(30, 90, 751, 351))
        self.pushButton_9 = QPushButton(self.Tab3)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(30, 460, 101, 31))
        self.pushButton_9.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pushButton_9.setIcon(icon2)
        self.label_21 = QLabel(self.Tab3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 10, 641, 30))
        self.label_21.setMinimumSize(QSize(641, 21))
        self.label_21.setMaximumSize(QSize(641, 30))
        self.label_21.setFont(font1)
        self.label_21.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.pushButton_10 = QPushButton(self.Tab3)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(30, 50, 121, 31))
        self.pushButton_10.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        icon5 = QIcon()
        icon5.addFile(u"Images/icons8-analysis-40 (1).png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_10.setIcon(icon5)
        self.pushButton_11 = QPushButton(self.Tab3)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(680, 460, 101, 31))
        self.pushButton_11.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        icon6 = QIcon()
        icon6.addFile(u"Images/icons8-view-48.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_11.setIcon(icon6)
        self.progressBar = QProgressBar(self.Tab3)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(160, 50, 621, 31))
        self.progressBar.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.progressBar.setValue(35)
        self.progressBar.setAlignment(Qt.AlignmentFlag.AlignBottom|Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(Qt.Orientation.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QProgressBar.Direction.BottomToTop)
        self.label_22 = QLabel(self.Tab3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(340, 250, 141, 16))
        icon7 = QIcon()
        icon7.addFile(u"Images/icons8-analysis-48.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tabWidget.addTab(self.Tab3, icon7, "")
        self.Tab2 = QWidget()
        self.Tab2.setObjectName(u"Tab2")
        self.graphicsView = QGraphicsView(self.Tab2)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(30, 90, 751, 351))
        self.label_9 = QLabel(self.Tab2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 10, 801, 30))
        self.label_9.setMaximumSize(QSize(801, 30))
        self.label_9.setFont(font1)
        self.label_9.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.pushButton_2 = QPushButton(self.Tab2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(660, 50, 121, 31))
        self.pushButton_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        icon8 = QIcon()
        icon8.addFile(u"Images/icons8-opened-folder-48.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_2.setIcon(icon8)
        self.label_10 = QLabel(self.Tab2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 60, 281, 16))
        self.pushButton_4 = QPushButton(self.Tab2)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(680, 460, 101, 31))
        self.pushButton_4.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        icon9 = QIcon()
        icon9.addFile(u"Images/icons8-next-48.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_4.setIcon(icon9)
        self.pushButton_5 = QPushButton(self.Tab2)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(30, 460, 101, 31))
        self.pushButton_5.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.pushButton_5.setIcon(icon2)
        self.label_23 = QLabel(self.Tab2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(340, 250, 141, 16))
        icon10 = QIcon()
        icon10.addFile(u"Images/icons8-upload-48.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tabWidget.addTab(self.Tab2, icon10, "")
        self.Tab1 = QWidget()
        self.Tab1.setObjectName(u"Tab1")
        self.Tab1.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label = QLabel(self.Tab1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 60, 101, 31))
        self.plainTextEdit = QPlainTextEdit(self.Tab1)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(170, 60, 211, 31))
        self.label_2 = QLabel(self.Tab1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 801, 30))
        self.label_2.setMaximumSize(QSize(801, 30))
        self.label_2.setFont(font1)
        self.label_2.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        self.plainTextEdit_2 = QPlainTextEdit(self.Tab1)
        self.plainTextEdit_2.setObjectName(u"plainTextEdit_2")
        self.plainTextEdit_2.setGeometry(QRect(170, 100, 211, 31))
        self.label_3 = QLabel(self.Tab1)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 100, 101, 31))
        self.label_4 = QLabel(self.Tab1)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 260, 101, 31))
        self.label_5 = QLabel(self.Tab1)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 140, 101, 31))
        self.plainTextEdit_4 = QPlainTextEdit(self.Tab1)
        self.plainTextEdit_4.setObjectName(u"plainTextEdit_4")
        self.plainTextEdit_4.setGeometry(QRect(170, 140, 211, 31))
        self.label_6 = QLabel(self.Tab1)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 180, 101, 31))
        self.plainTextEdit_5 = QPlainTextEdit(self.Tab1)
        self.plainTextEdit_5.setObjectName(u"plainTextEdit_5")
        self.plainTextEdit_5.setGeometry(QRect(170, 180, 211, 31))
        self.comboBox = QComboBox(self.Tab1)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(170, 220, 211, 31))
        self.label_7 = QLabel(self.Tab1)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 220, 141, 31))
        self.textEdit = QTextEdit(self.Tab1)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(430, 90, 351, 171))
        self.label_8 = QLabel(self.Tab1)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(430, 60, 101, 31))
        self.pushButton = QPushButton(self.Tab1)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(680, 460, 101, 31))
        self.pushButton.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.pushButton.setIcon(icon9)
        self.calendarWidget = QCalendarWidget(self.Tab1)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(170, 260, 211, 181))
        font3 = QFont()
        font3.setPointSize(7)
        font3.setBold(False)
        font3.setKerning(True)
        self.calendarWidget.setFont(font3)
        self.calendarWidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.calendarWidget.setHorizontalHeaderFormat(QCalendarWidget.HorizontalHeaderFormat.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        icon11 = QIcon()
        icon11.addFile(u"Images/icons8-information-48.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tabWidget.addTab(self.Tab1, icon11, "")
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 10, 111, 21))
        self.label_11.setPixmap(QPixmap(u"Images/kinectrics-logo-colour.svg"))
        self.label_11.setScaledContents(True)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 30, 241, 21))
        self.label_12.setFont(font2)
        self.label_12.setScaledContents(True)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Software Fuel Bundle", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"Download Report", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"View and Download Report", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"[PDF Preview of the Report]", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Additional Comments :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab5), QCoreApplication.translate("MainWindow", u"Reports", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"[Frame from Video]", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"S-1023", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Upper Quadrant", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Defect Type :", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Defect Details", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Defect Size :", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Sheath Number :", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Surface Crack", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"2.3 mm", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Defect Location :", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"Approve", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"Reject", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Review Analysis Results", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Sheath Number", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Defect Type", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Defect Size", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Defect Location", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Status", None));

        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        ___qtablewidgetitem5 = self.tableWidget.item(0, 0)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"S-1023", None));
        ___qtablewidgetitem6 = self.tableWidget.item(0, 1)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Surface Crack", None));
        ___qtablewidgetitem7 = self.tableWidget.item(0, 2)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"2.3 mm", None));
        ___qtablewidgetitem8 = self.tableWidget.item(0, 3)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Upper Quadrant", None));
        ___qtablewidgetitem9 = self.tableWidget.item(0, 4)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Approved", None));
        self.tableWidget.setSortingEnabled(__sortingEnabled)

        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"Submit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab4), QCoreApplication.translate("MainWindow", u"Results", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Video Analysis and Processing", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"Start Analysis", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"View Results", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"[Analyzed Video Player]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab3), QCoreApplication.translate("MainWindow", u"Analysis", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Upload and Preview Video", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Upload Video ", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"YourPC/Location/renadom/location/VideoName", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"[Uploaded Video Player]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab2), QCoreApplication.translate("MainWindow", u"Video Upload", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Inspector Name :", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Inspection Information", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Channel :", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Inspection Date :", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Station Unit :", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Serial Number :", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Reason for Inspection :", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Notes :", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab1), QCoreApplication.translate("MainWindow", u"Information", None))
        self.label_11.setText("")
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Fuel Bundle Software", None))
    # retranslateUi

